version: '3.5'
services:
  backend:
    container_name: sp-payment-backend
    image: "stellar-payment/sp-payment-be:$BUILD_TAG"
    build: 
      context: .
      args:
        USERNAME_GITHUB: 
        TOKEN_GITHUB: 
        BUILD_TAG: $BUILD_TAG 
        BUILD_TIMESTAMP: $BUILD_TIMESTAMP
    ports:
      - "7003:7780"
    volumes:
      - /home/fuyuna/services/sp-payment/data:/data
      - /home/fuyuna/services/sp-payment/conf:/app/conf
      - /home/fuyuna/services/sp-payment/migrations:/app/migrations

networks:
  default:
    name: stellar-net
    external: true