version: '3.5'
services:
  backend:
    container_name: sp-payment-backend
    image: "stellar-payment/sp-payment-be:$BUILD_TAG"
    build: 
      context: .
      args:
        USERNAME_GITHUB: 
        TOKEN_GITHUB: 
        BUILD_TAG: $BUILD_TAG 
        BUILD_TIMESTAMP: $BUILD_TIMESTAMP
    ports:
      - "7002:7780"
networks:
  default:
    name: stellar-net
    external: true